name: Python Code Quality Check

on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install flake8
      run: pip install flake8
    - name: Run flake8
      run: flake8 . > /dev/null 2>&1 || (echo "Errors detected" && flake8 . > flake8_output.txt)
    - name: Display flake8 errors if any
      if: failure()
      run: cat flake8_output.txt
