name: Python Code Quality and Security Check for Push

on: push

jobs:
  check_code_quality_and_security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Récupère tout l'historique pour les comparaisons de commits

    - name: Get changed files
      id: changed-files
      run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.py$' | xargs)
          echo "changed_files=$changed_files" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install flake8 and Bandit
      run: |
        pip install flake8
        pip install bandit

    - name: Run flake8 and set failure flag
      if: env.changed_files
      run: |
          flake8 $changed_files > flake8_output.txt 2>&1 || echo "flake8 Errors detected"
          if [ -s flake8_output.txt ]; then
            echo "FLAKE8_FAILED=1" >> $GITHUB_ENV
          fi
  
    - name: Display flake8 errors if any
      if: env.FLAKE8_FAILED == '1'
      run: cat flake8_output.txt
  
    - name: Run Bandit and set failure flag
      if: env.changed_files
      run: |
          bandit -r $changed_files -o bandit_output.txt || echo "BANDIT_FAILED=1" >> $GITHUB_ENV
  
    - name: Display Bandit errors if any
      if: env.BANDIT_FAILED == '1'
      run: cat bandit_output.txt

    - name: Success or failure 
      if: env.BANDIT_FAILED=='1' || env.FLAKE8_FAILED=='1'
      run: exit 1
