name: Check compilation and linting

on: pull_request

jobs:
  check_code_pull_request_for_compilation:
    runs-on: ubuntu-latest
    steps:
    - name: Get all files
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install ruff

    - name: Check compilation
      run: |
        echo "Starting compilation check..."
        python3 -m compileall . -f -r 2

    - name: Run Flake8 linting
      run: |
        echo "Running Flake8..."
        ruff check . --select F --ignore F401,F403,F405,F601 
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Pyright
      run: npm install -g pyright

    - name: Run Pyright
      run: pyright .