name: Python Code Quality and Security Check

on: [push]

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install flake8 and Bandit
      run: |
        pip install flake8
        pip install bandit
    - name: Get changed Python files for pull request
      id: files
      run: |
        if git rev-parse HEAD^ > /dev/null 2>&1; then
          git diff --name-only HEAD^ HEAD | grep '\.py$' > changed_files.txt
        else
          git diff --name-only HEAD | grep '\.py$' > changed_files.txt
        fi
        if [ -s changed_files.txt ]; then
          echo "::set-output name=files::$(cat changed_files.txt)"
        else
          echo "::set-output name=files::"
        fi
    - name: Run flake8 on changed files
      run: |
        if [ -n "${{ steps.files.outputs.files }}" ]; then
          flake8 ${{ steps.files.outputs.files }} > /dev/null 2>&1 || (echo "flake8 Errors detected" && flake8 ${{ steps.files.outputs.files }} > flake8_output.txt)
        fi
    - name: Run Bandit on changed files
      run: |
        if [ -n "${{ steps.files.outputs.files }}" ]; then
          bandit -r ${{ steps.files.outputs.files }} -o bandit_output.txt
        fi
    - name: Display Code Quality or Style errors if any
      if: failure()
      run: cat flake8_output.txt
    - name: Display Security errors if any
      if: always()
      run: |
        if [ -s bandit_output.txt ]; then
          cat bandit_output.txt
        fi
