name: Python Code Quality and Security Check for PR
on: pull_request
jobs:
  check_code_pull_request:
    runs-on: ubuntu-latest
    steps:
    - name: Get all files
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install Ruff, Bandit, Pylint, sqlfluff, and Black
      run: |
        pip install ruff==0.0.78 # Assurez-vous d'utiliser la dernière version
        pip install bandit
        pip install pylint
        pip install sqlfluff
        pip install black

    - name: Check style of the code (Python) with Ruff
      run: ruff .

    - name: Check code formatting with Black
      run: black --check .

    - name: Check quality of the code (Python) with Pylint
      run: pylint **/*.py

    - name: Check security issues (Python) with Bandit
      run: bandit -r .

    - name: Check style of the code (SQL) with sqlfluff
      run: |
          find . -name '*.sql' -print0 | xargs -0 sqlfluff lint --dialect bigquery
