name: Pull After PR Merge to Main

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  pull-on-merge:
    runs-on: self-hosted
    if: github.event.pull_request.merged == true
    steps:
    - name: Change directory and pull latest changes
      run: |
        cd dossier_du_projet
        git pull 
