name: Pull After PR Merge to Main

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  pull-on-merge:
    runs-on: [self-hosted,DESK-TEST-MTM]
    if: github.event.pull_request.merged == true
    steps:
    - name: Change directory and pull latest changes
      run: |
        cd C:\Users\EtienneMALACARNE\code\test_runner_folder\test_action
        git pull 
