name: Python Code Quality and Security Check

on: [push]

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

    - name: Get changed files
      id: changed-files
      run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.py$' | xargs)
          echo "changed_files=$changed_files" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install flake8 and Bandit
      run: |
        pip install flake8
        pip install bandit

    - name: Run flake8
      if: env.changed_files
        
      run: |
          flake8 $changed_files > flake8_output.txt 2>&1 || echo "flake8 Errors detected"
      
  
    - name: Display flake8 errors if any
      if: env.changed_files && failure()
      run: cat flake8_output.txt

    - name: Run Bandit
      if: env.changed_files
      run: |
          bandit -r $changed_files -o bandit_output.txt || echo "Bandit Issues detected"
          
  
    - name: Display Bandit errors if any
      if: env.changed_files && failure()
      run: cat bandit_output.txt