name: Python Code Quality and Security Check

on: [push]

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

    - name: Get changed files
      id: changed-files
      run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '\.py$' | xargs)
          echo "changed_files=$changed_files" >> $GITHUB_ENV

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install flake8 and Bandit
      run: |
        pip install flake8
        pip install bandit

    - name: Run flake8
      if: env.changed_files
        
      run: |
          flake8 $changed_files > flake8_output.txt 2>&1 || echo "flake8 Errors detected"
      
    - name: Run Bandit
      if: env.changed_files
      run: |
          bandit -r $changed_files -o bandit_output.txt || echo "Bandit Issues detected"
  
    - name: Check for flake8 errors
      if: env.changed_files
      run: |
          if [ -s flake8_output.txt ]; then
            echo "::error::flake8 issues detected"
            cat flake8_output.txt
          fi
  
    - name: Check for Bandit issues
      if: env.changed_files
      run: |
          if [ -s bandit_output.txt ]; then
            echo "::error::Bandit issues detected"
            cat bandit_output.txt
          fi
